### ISSUE TITLE
Import is missing in generated app

### ISSUE THREAD

**Issue by jamilxt** [sayemoid/kmm-booster-template#1]
![image](https://github.com/user-attachments/assets/f4efd379-7b46-4e85-a0cd-4a1003b539c5)

This particular import is missing while generating new app using the script

import cafe.adriel.voyager.koin.koinScreenModel

**Comment by jamilxt** [comment]
Also, can you please share the gentool.jar's source code, if it's okay with you.

**Comment by sayemoid** [comment]
Thanks for notifying. I'll try to check it when I get some time.
About source code of generator tool, I'll share that too.

**Comment by jamilxt** [comment]
Sorry, I am late to give the PR.

**Comment by jamilxt** [comment]
As the imports are in ascending order (a-z), I think you may consider merging my PR  #2  for this issue.

**Comment by jamilxt** [comment]
@sayemoid  Thank you so much for reviewing the PR. Looking forward to contribute more in this project.

**Comment by sayemoid** [comment]
@jamilxt you'll find source code for tools module here
https://github.com/teambankrupt/gentool/tree/master

**Comment by jamilxt** [comment]
@sayemoid Thank you so much.
